version: '3.7'

services:
  app:
    container_name: ayudaap-api
    build: .
    ports: 
      - "80:8080"
    restart: on-failure
    volumes: 
      #- "$PWD:/go/src/Ayudaap.org"
       - ayudaa-api-data:/usr/src/app
    networks: 
      - ayudaap-net
    depends_on:
      - db

  db:
    container_name: ayudaap-db
    image: mongo
    ports: 
      - 27017:27017
    volumes: 
      - ayudaap-db-vol:/data/db
    networks: 
      - ayudaap-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_INIT}
    

networks: 
  ayudaap-net:
    driver: bridge
volumes: 
  ayudaa-api-data:
  ayudaap-db-vol:
