version: '3.7'

services:
  app:
    container_name: ayudaap-api
    image: golang
    ports: 
      - "80:8080"
    volumes: 
      - "$PWD:/go/src/Ayudaap.org"
    working_dir: /go/src/Ayudaap.org
    command: go run main.go
    networks: 
      - ayudaap-net
    depends_on:
      - db
    links:
      - db

  db:
    container_name: ayudaap-db
    image: mongo
    ports: 
      - 27017:27017
    volumes: 
      - ayudaa-db-vol:/data/db
    networks: 
      - ayudaap-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Testing1+
    

networks: 
  ayudaap-net:
volumes: 
  ayudaa-db-vol: